<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE torneosATP [
	<!ELEMENT torneosATP (torneo+)>
	<!ELEMENT torneo (nombre, fechaIni, fechaFin, puntosATP, cuadro, partidos)>
	
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT fechaIni (#PCDATA)>
	<!ELEMENT fechaFin (#PCDATA)>
	
	<!ELEMENT puntosATP (ronda+)>
	<!ELEMENT ronda (#PCDATA)>
	<!ATTLIST ronda puntos CDATA "0">
	
	<!ELEMENT cuadro (cruce+)>
	<!ELEMENT cruce (jugador+)>
	<!ATTLIST cruce numero ID #IMPLIED>
	<!ELEMENT jugador (#PCDATA)>
	<!ATTLIST jugador nombre CDATA "sin nombre">
	<!ATTLIST jugador rankingTorneo CDATA "0">
	
	<!ELEMENT partidos (partido+)>
	<!ELEMENT partido (tipo, jugadores, resultado)>
	<!ATTLIST partido estado (en_juego | finalizado)>
	
	<!ELEMENT tipo (#PCDATA)>
	
	<!ELEMENT jugadores (lado1, lado2)>
	<!ELEMENT lado1 (jugador)>
	<!ELEMENT jugador (#PCDATA)>
	<!ATTLIST jugador nombre CDATA "sin nombre">
	<!ATTLIST jugador rankingTorneo CDATA "0">
	<!ELEMENT lado2 (jugador)>
	<!ELEMENT jugador (#PCDATA)>
	<!ATTLIST jugador nombre CDATA "sin nombre">
	<!ATTLIST jugador rankingTorneo CDATA "0">
	
	<!ELEMENT resultado (set+)>
	<!ELEMENT set (juegos)>
	<!ATTLIST set numero ID "1">
	<!ELEMENT juegos (puntosJuego?)>
	<!ATTLIST juegos lado1 CDATA "0">
	<!ATTLIST juegos lado2 CDATA "0">
	<!ELEMENT puntosJuego (#PCDATA)>
	<!ATTLIST puntosJuego lado1 CDATA "0">
	<!ATTLIST puntosJuego lado2 CDATA "0">
]>

<torneosATP>
    <torneo>
        <nombre>Mutua Madrid Open</nombre>
        <fechaIni>2026-04-22</fechaIni>
        <fechaFin>2026-05-03</fechaFin>

        <puntosATP>
            <ronda puntos="50">2da ronda</ronda>
            <ronda puntos="100">3ra ronda</ronda>
            <ronda puntos="200">cuartos</ronda>
        </puntosATP>

        <cuadro>
            <cruce numero="1">
                <jugador nombre="Carlos Alcaraz" rankingTorneo="1"/>
                <jugador nombre="Jugador 32" rankingTorneo="32"/>
            </cruce>
        </cuadro>

        <partidos>
            <partido estado="en_juego">
                <tipo>individual masculino</tipo>

                <jugadores>
                    <lado1>
                        <jugador nombre="Carlos Alcaraz" rankingTorneo="1"/>
                    </lado1>
                    <lado2>
                        <jugador nombre="Jugador 32" rankingTorneo="32"/>
                    </lado2>
                </jugadores>

                <resultado>
                    <set numero="1">
                        <juegos lado1="6" lado2="4"/>
                    </set>
                    <set numero="2">
                        <juegos lado1="3" lado2="2">
                            <puntosJuego lado1="40" lado2="30"/>
                        </juegos>
                    </set>
                </resultado>
            </partido>
        </partidos>
    </torneo>
</torneosATP>
